---
version: "3.8"
services:
  wetty:
    image: hikariai/wetty:latest
    build:
      context: .
      dockerfile: containers/wetty/Dockerfile
    tty: true
    working_dir: /usr/src/app
    ports:
      - "3000:3000"

  neovim-server:
    image: hikariai/nvim-server:v1.0.0
    build:
      context: .
      dockerfile: containers/nvim-server/Dockerfile
    tty: true
    working_dir: /workspace
    ports:
      - "6080:3000"
